"use strict";
let m = 2 + (7 ** 3);
console.log(m);
let n = 20;
console.log(n);
console.log(`El resultado de m + n es: ${m + n}`);
let Control1 = 5.5;
let Control2 = 4.1;
let Control3 = 6.4;
let total = (Control1 + Control2 + Control3);
let Promedio = (Control1 + Control2 + Control3) / total;
console.log(`El promedio es ${Promedio}`);
let mascota = 'perritos';
let cantidad = 10;
let mensaje = `Yo tenia ${cantidad} ${mascota}`;
console.log(mensaje);
let dolar = 787.65;
let pesos = 10000;
let dolaresObtenidos = pesos / dolar;
console.log(`La cantidad de dolares obtenidos es: $${dolaresObtenidos}`);
let PI = 3.14;
let radio = 10;
let perimetro = 2 * PI * radio;
let area = PI * radio ** 2;
PI = 3.1415;
console.log(perimetro);
console.log(area);
