"use strict";
let A = 10;
let B = 2;
console.log(`El resultado de A-B es: ${A - B}`);
console.log(`El resultado de A*B es: ${A * B}`);
console.log(`El resultado de A/B es: ${A / B}`);
console.log(`El resultado de A-B es: ${A ** B}`);
console.log(`El resultado de A-B es: ${A % B}`);
const numeroConstante = 45;
const primerDigito = numeroConstante % 10;
const segundoDigito = (numeroConstante - primerDigito) / 10;
console.log(`El número ${numeroConstante} invertido es ${primerDigito}${segundoDigito}`);
const numeroConstante_2 = 685;
const unidad = numeroConstante_2 % 10;
const restoUnidad = numeroConstante_2 % 100;
const centena = (numeroConstante_2 - restoUnidad) / 100;
const decena = ((numeroConstante_2 % 100) - (numeroConstante % 10)) / 10;
console.log(`El numero ${numeroConstante_2} invertido es ${unidad}${decena}${centena}`);
const poblacacionInicial = 15;
const minutos = 3;
const num = 20;
const poblacionFinal = poblacacionInicial * (5 ** minutos) + num;
console.log(poblacionFinal);
const a = 2;
const exprecion1 = (((4 + 5) * a - 20 / 50) ** a / 5);
console.log(exprecion1);
const exprecion2 = (45 + (10 ** 5) - 55) / ((30 * 8) - a) - (a ** (5 / 4));
console.log(exprecion2);
let op1 = ((1.5 - 35)) ** a;
let op2 = (a ** 3 / 15);
const exprecion3 = op1 + op2;
console.log(exprecion3);
